from . import sale_payment_instructions
from . import sale_dispatcher
from . import sale_booking_conveyance
from . import sale_order_type
from . import sale_order
from . import sale_order_filter
from . import sale_order_domain
from . import sale_certificate_of_analysis
from . import sale_place_of_delivery
from . import sale_shipment
from . import res_partner
from . import ir_sequence
from . import sale_order_line
from . import stock_picking