# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Etilfarma Installation Modules",
    "summary": """
        One module to rule them all.
        Etilfarma Full installation""",
    "author": "Calyx Servicios S.A.",
    "maintainers": ["JhoneM"],
    "website": "http://odoo.calyx-cloud.com.ar/",
    "license": "AGPL-3",
    "category": "Custom",
    "version": "11.0.1.0.2",
    "development_status": "Production/Stable",
    "application": False,
    "installable": True,
    "external_dependencies": {"python": ["num2words"], "bin": []},
    "depends": [
        "backend_theme_v11",
        "foreign_trade",
        "hr",
        "board",
        "account_invoice_supplier_block",
        "l10n_aeroo_einvoice_custom_output",
        "product_expiry_months",
        "foreign_purchase_order_alerts",
        "partner_supplier_foreign_fields",
        "purchase_and_sale_datetime_to_date",
        "purchase_exception_extend",
        "purchase_menu_remove_rfq",
        "purchase_order_booking_email",
        "purchase_order_dates_restriction",
        "purchase_order_foreign_report",
        "purchase_order_line_hide_date_planned",
        "purchase_request_extension",
        "purchase_rename_to_comex",
        "stock_picking_date_picker",
        "stock_picking_lot_extension",
        "etilfarma_translations_fixes",
    ],
    "data": ["data/translates.xml"],
}
