from . import purchase_order
from . import purchase_place_of_delivery
from . import purchase_delivery_chanel
from . import purchase_packaging
from . import purchase_shipment
from . import purchase_packing_list
from . import res_config_settings
from . import purchase_certificate_of_analysis
from . import purchase_import_license
from . import product_template
from . import account_invoice
